### ISSUE TITLE
SetValue is doing a lot of overhead

### ISSUE THREAD

**Issue by poohbear80** [petterek/lzy#4]
Every time setvalue is called there is a lot of reflection going on. 

http://stackoverflow.com/questions/12767091/why-are-propertyinfo-setvalue-and-getvalue-so-slow/12860249#12860249

We think this is impacting performance on our new objects in our system

**Comment by petterek** [comment]
Reflection is only done once for each query and object type..

**Comment by petterek** [comment]
Ref to code?

**Comment by poohbear80** [comment]
@FredrikTheEvil

**Comment by petterek** [comment]
Line 57 in datafiller..
Could be replaced with something more efficinet..

**Comment by petterek** [comment]
Should be fairly easy to optimize.
